version: "3.9"
services:
  sntt:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    environment:
      TCPADDR: "localhost:1111"
      HTTPPORT: ":2222"
    entrypoint: "sntt"
    command: [server]
